name: Coursier

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install PostgreSQL
        run: echo "/usr/lib/postgresql/13/bin" >> $GITHUB_PATH

      - name: Start Postgres
        run: |
          mkdir -p /tmp/pgsql/data
          ls -la /usr/lib/postgresql/13/
          ls -la /usr/lib/postgresql/13/share/
          ls -la /usr/lib/postgresql/13/share/postgresql
          cp /usr/lib/postgresql/13/share/postgresql/postgresql.conf.sample /tmp/pgsql/data/postgresql.conf
          postgres -D /tmp/pgsql/data
