name: Coursier

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PGDATA: /var/lib/postgresql/13/main
    steps:
      - uses: actions/checkout@master

      - name: Install PostgreSQL
        run: |
          sudo chmod -R 777 /var/lib/postgresql/13/main
          echo "/usr/lib/postgresql/13/bin" >> $GITHUB_PATH
          
      - run: whoami    
      - run: ls -la /etc/postgresql/13/main
      - run: sudo cp -R /etc/postgresql/13/main/* /var/lib/postgresql/13/main
      - run: sudo chmod -R 0700 /var/lib/postgresql/13/main
      - run: sudo chown -R runner:runner /var/lib/postgresql/13/main
      - run: sudo chown -R runner:runner /var/lib/postgresql/13/main/
      - run: sudo chown -R runner:runner /var/lib/postgresql/13/
      - run: ls -la /var/lib/postgresql/13/main
      - run: |
          # > It happened to me and it turned out that I removed erroneously the postgres user from "ssl-cert" group, set it back with
          sudo gpasswd -a runner ssl-cert

          # Fixed ownership and mode
          sudo chown runner:ssl-cert  /etc/ssl/private/ssl-cert-snakeoil.key
          sudo chmod 740 /etc/ssl/private/ssl-cert-snakeoil.key
        
      - run: postgres --hba_file=pg_hba.conf --unix_socket_directories=/tmp
          
          
          
