name: Coursier

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PGDATA: /var/lib/pgsql/data
    steps:
      - uses: actions/checkout@master

      - name: Install PostgreSQL
        run: echo "/usr/lib/postgresql/13/bin" >> $GITHUB_PATH

      - name: Start Postgres
        run: |
          mkdir -p /tmp/postgres
          cat /etc/postgresql/13/main/postgresql.conf
          ls -la /var/lib/pgsql/data
          postgres --hba_file=pg_hba.conf --unix_socket_directories=/tmp
