name: Coursier

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PGDATA: /tmp/pdata/main
    steps:
      - uses: actions/checkout@master

      - name: Install PostgreSQL
        run: |
          mkdir -p /tmp/postgres
          mkdir -p /tmp/pdata
          #cp -R /usr/lib/postgresql/13 /tmp/postgres
          #sudo chmod -R 777 /tmp/postgres
          sudo cp -R /var/lib/postgresql/13/main /tmp/pdata
          sudo chmod -R 777 /tmp/pdata
          echo "/usr/lib/postgresql/13/bin" >> $GITHUB_PATH
          

      - run: sudo ls -la /tmp/pdata/main
      - run: postgres --hba_file=pg_hba.conf --unix_socket_directories=/tmp
          
          
          
