name: Coursier

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PGDATA: /tmp/postgres
    steps:
      - uses: actions/checkout@master

      - name: Install PostgreSQL
        run: |
          mkdir -p /tmp/postgres
          echo "/usr/lib/postgresql/13/bin" >> $GITHUB_PATH

      - name: Init Db
        run: initdb -D /tmp/postgres
      
      - run: ls -la /tmp/postgres
    
      - run: postgres --hba_file=pg_hba.conf --unix_socket_directories=/tmp
        
          
          
          
