name: Coursier

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Test
        run: |
          filename="/usr/bin/script.kts"
          echo $filename
          cname=${filename%.*}
          echo $cname
          cname_lower="$(tr '[:lower:]' '[:upper:]' <<<"${cname:0:1}")${cname:1}"
          echo $cname_lower

