name: Coursier

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install PostgreSQL
        run: echo "/usr/lib/postgresql/13/bin" >> $GITHUB_PATH

      - name: Start Postgres
        run: |
          mkdir -p /tmp/pgsql/data
          postgres -D /usr/local/pgsql/data
