name: Coursier

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install redis-server
    - run: redis-server -v
    - run: command -v redis-server
    - run: command -v redis-server1
