name: Coursier

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PGDATA: /tmp/postgres/
    steps:
      - uses: actions/checkout@master

      - name: Install PostgreSQL
        run: echo "/usr/lib/postgresql/13/bin" >> $GITHUB_PATH

      - name: Start Postgres
        run: |
          mkdir -p /tmp/pgsql/data
          ls -la /etc/postgresql/13/main
          cp /etc/postgresql/13/main/postgresql.conf /tmp/pgsql/data
          ls -la /tmp/pgsql/data
          postgres --hba_file=pg_hba.conf --unix_socket_directories=/tmp
