name: Coursier

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PGDATA: /var/lib/postgresql/13/main
    steps:
      - uses: actions/checkout@master

      - name: Install PostgreSQL
        run: |
          sudo chmod -R 777 /var/lib/postgresql/13/main
          echo "/usr/lib/postgresql/13/bin" >> $GITHUB_PATH
          
      - run: postgres --hba_file=pg_hba.conf --unix_socket_directories=/tmp
          
          
          
