name: Coursier

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11

      - run: |
          wget http://download.redis.io/releases/redis-6.0.4.tar.gz
          tar xzf redis-6.0.4.tar.gz
          cd redis-6.0.4
          make
          echo "::add-path::$(pwd)/src/redis-server"

      - run: echo $PATH
      - run: redis-server -v
      - run: sudo sbt docs/run
