name: Coursier

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Test
        run: |
          sudo apt-get install postgresql postgresql-contrib -y
          psql --version
          postgres --version

