name: Release

on:
  push:
    branches:
      - master

# on:
#   release:
#   push:
#     tags:
#       - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11

      # - name: Github Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_RELEASE }}
      #   run: sbt githubRelease

      - name: Docs Publish
        run: |
          echo 'echo $GITHUB_TOKEN' > $HOME/.git-askpass
          chmod +x $HOME/.git-askpass
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Action"
          sbt ghpagesPushSite
          
        env:
          GITHUB_TOKEN: $${{ secrets.GITHUB_RELEASE }}
          GIT_ASKPASS: "$HOME/.git-askpass"
