name: Release

on:
  push:
    branches:
      - master

# on:
#   release:
#   push:
#     tags:
#       - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11

      # - name: Github Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_RELEASE }}
      #   run: sbt githubRelease

      - name: Credenitals Helper
        run: |
          echo $GITHUB_TOKEN > ~/.git-askpass
        env:
          GITHUB_TOKEN: $${{ secrets.GITHUB_RELEASE }}

      - name: Docs Publish
        run: sbt ghpagesPushSite
        env:
          GIT_ASKPASS: ~/.git-askpass
